export const KODA_VERSION = "0.1.0" as const;

export const RUNTIME_MANIFEST_SCHEMA_VERSION = 1 as const;
export const INTEGRITY_INVENTORY_SCHEMA_VERSION = 1 as const;
export const BUNDLE_DOCTOR_SCHEMA_VERSION = 1 as const;
export const MACOS_RELEASE_METADATA_SCHEMA_VERSION = 1 as const;
export const MACOS_RELEASE_SET_SCHEMA_VERSION = 1 as const;
export const NODE_RELEASE_PROVENANCE_SCHEMA_VERSION = 1 as const;
export const MACOS_CODE_SIGNATURE_EVIDENCE_SCHEMA_VERSION = 1 as const;
export const MACOS_NOTARIZATION_EVIDENCE_SCHEMA_VERSION = 1 as const;
export const MACOS_PUBLIC_RELEASE_PROVENANCE_SCHEMA_VERSION = 1 as const;
export const MACOS_PREVIEW_STATE_SCHEMA_VERSION = 1 as const;
export const MACOS_PREVIEW_ACTIVATION_SCHEMA_VERSION = 1 as const;
export { NATIVE_EXECUTOR_PROTOCOL_VERSION } from "@koda/protocol";
